Import('env')

sourceList = ['cvBlobModule', 'PanTiltCameraClass', 'PhidgetServoClass', ]

#-------------------------------------------------------------------------------
# Nothing to modify below this line
#-------------------------------------------------------------------------------

for sourceName in sourceList:
   SConscript('./%s/SConscript' % sourceName)

Export('env')